export const STORAGE_TABLE_SETTINGS = 'tableSettings';

export const DEFAULT_TABLE_SETTINGS = {
  ids: [
    'loosesPercent',
    'position',
    'picture',
    'sku',
    'isFavorite',
    'chartSales',
    'product',
    'brand',
    'merchant',
    'group',
    'remains',
    'reviews',
    'rating',
    'price',
  ],
  order: [
    'loosesPercent',
    'position',
    'picture',
    'sku',
    'isFavorite',
    'chartSales',
    'product',
    'brand',
    'merchant',
    'group',
    'remains',
    'reviews',
    'rating',
    'price',
  ],
  size: [100, 100, 80, 100, 60, 200, -1, 100, 100, 100, 100, 100, 100],
  select: [],
  scroll: {
    x: 0,
    y: 0,
  },

  filter: {
    loosesPercent: '',
    position: '',
    product: '',
    brand: '',
    merchant: '',
    group: '',
    remains: '',
    reviews: '',
    rating: '',
    price: '',
    sku: '',
    any: '',
    isFavorite: false,
  },
  hidden: [],
};
